version: "3.9"
services:
  dashboard_crowdcareaid:
    image: "crowdcareaid:${TAG}latest"
    container_name: '${TAG}dashboard_crowdcareaid'
    ports:
      - 172.17.0.1:${WEB_PORT}:3000
    restart: always
# ADMIN Containers
  # admin_dashboard_crowdcareaid:
  #   image: "crowdcareaid-admin:${TAG}latest"
  #   container_name: '${TAG}admin_dashboard_crowdcareaid'
  #   ports:
  #     - 172.17.0.1:${ADMIN_PORT}:80
  #   restart: always