import './global.css';

import { PT_Serif, Poppins } from 'next/font/google';
import { Toaster } from '@crowdcareaid-frontend/next-components';
const pt_serif = PT_Serif({
  subsets: ['latin'],
  style: 'normal',
  weight: ['400', '700'],
  variable: '--font-pt_serif',
});

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['400'],
});

export const metadata = {
  title: 'Welcome to crowdcareaid-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${pt_serif.variable} ${poppins.variable}`}>
      <body>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
